---
# Router URL and credentials
router:
   sempUrl: "http://localhost:8080"
   sempUser: "admin"
   sempPassword: "admin"

# VPN to work with
vpn:
   msgVpnName: "TestVPN"

# Template values for creating artifacts
templates:
   # Queue template to use for creating queues.
   # These values can be overwritten in the input CSV file
   # Any property not listed here / input CSV will use Solace defaults
   queue:
      accessType: "non-exclusive"
      deadMsgQueue: "#DEAD_MSG_QUEUE"
      maxBindCount: 10
      maxDeliveredUnackedMsgsPerFlow: 1000
      maxMsgSize: 1000000
      maxMsgSpoolUsage: 1234
      maxRedeliveryCount: 2
      maxTtl: 0
      owner: "solace-cloud-client"
      permission: "no-access"
      redeliveryEnabled: true
      respectTtlEnabled: true
      subscriptionTopic: ""
   dmqueue:
      accessType: "exclusive"
      deadMsgQueue: "#DEAD_MSG_QUEUE"
      maxBindCount: 1
      maxDeliveredUnackedMsgsPerFlow: 1000
      maxMsgSize: 1000000
      maxMsgSpoolUsage: 5000
      maxRedeliveryCount: 0
      maxTtl: 0
      owner: "solace-cloud-client"
      permission: "no-access"
      redeliveryEnabled: false
      respectTtlEnabled: false
      subscriptionTopic: ""

# SEMP internal stuff. Don't change unless you know what you're doing
semp:         
   pageSize: 100
   configUrl: "SEMP/v2/config"
   monitorUrl: "SEMP/v2/monitor"
   actionUrl: "SEMP/v2/action"